### PR TITLE
Use composer docker image to create project

### LINKED ISSUE #30: Getting InvalidArgumentException when creating a new composer project inside container
The reason being that the target folder is not empty.

image

### PR DESCRIPTION
**Pull request by wachterjohannes**
Fixes #30

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@nnatter what do you think?

**Review by niklasnatter — APPROVED** [review]

**Comment by niklasnatter** [comment]
this leads to:
```
[RuntimeException]
An error occurred when executing the "'cache:clear --no-warmup'" command:

06:59:14 ERROR     [console] Error thrown while running command "--ansi cache:clear --no-warmup". Message: "Gd not installed" ["exception" => Imagine\Exception\RuntimeException { …},"command" => "--ansi cache:clear --no-warmup","message" => "Gd not installed"]

In Imagine.php line 172:
Gd not installed
```

**Comment by wachterjohannes** [comment]
@nnatter when do you get this error?

**Comment by niklasnatter** [comment]
when executing `docker run --rm --interactive --tty --volume $PWD/project:/app composer create-project sulu/sulu-minimal .`

this is because the clearing the cache (in the `post-install-cmd`) somehow depends on GD and there is no GD installed in the composer image.

**Comment by niklasnatter** [comment]
we could execute `create-project` with `--no-scripts` and then run `post-install-cmd` in the php container?

**Pull request closed without merging**
